vich_uploader:
    db_driver: orm

    mappings:
       afbeeldingen:
          uri_prefix: 'https://wdev2.be/roel21/eindwerk/images/afbeeldingen'
          upload_destination: '/var/www/html/wdev2.be/web/roel21/eindwerk/images/afbeeldingen'
